export const SVG_ARROW_HEIGHT = 10;
export const CODE_SNAPSHOT_DEBOUNCE_MS = 1000;
export const SUBMIT_UPDATE_HISTORY_INTERVAL_MS = 1000 * 60;
export const DEFAULT_EMBEDDED_CODE_DIV_WIDTH = 350;
export const DEFAULT_EMBEDDED_CODE_DIV_HEIGHT = 400;